In [1]:
#1 Import Pandas

import pandas as pd

In [2]:
#2 Create a Series

data = pd.Series([10,20,30,40,50])

print(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
#3 Create a DataFrame

student = {
    "Name":["Ram","Shyam","Anu"],
    "Age":[20,21,19],
    "Marks":[85,90,78]
}

df = pd.DataFrame(student)
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     90
2    Anu   19     78

In [6]:
#4 Read CSV File

df = pd.read_csv("Iris.csv")
print(df[1:6])

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [8]:
#4 Display First Five records

df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
#5 Display Last Five Records

df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
#6 Dataset Information

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

In [11]:
#7 Statistical Summary

print(df.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
#8 Display Columns

print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [16]:
#9 Select Columns

print(df["SepalLengthCm"])

print("\n",df[["SepalLengthCm","PetalLengthCm"]])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

      SepalLengthCm  PetalLengthCm
0              5.1            1.4
1              4.9            1.4
2              4.7            1.3
3              4.6            1.5
4              5.0            1.4
..             ...            ...
145            6.7            5.2
146            6.3            5.0
147            6.5            5.2
148            6.2            5.4
149            5.9            5.1

[150 rows x 2 columns]

In [18]:
#10 Select Rows

print(df.iloc[0])

print("\n",df.iloc[0:5])

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
#11 Filter Data

print(df[df["Species"]=="setosa"])

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [23]:
#12 Sorting

df.sort_values(by="SepalLengthCm")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [33]:
#13 Add New Column

df["Total"] = df["SepalLengthCm"] + df["PetalLengthCm"]

df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Total
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4

In [34]:
#14 Delete Column

df.drop("Total",axis=1,inplace=True)

df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [35]:
#15 Missing Values

print(df.isnull().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [36]:
#16 Fill Missing Values

df.fillna(0,inplace=True)

In [37]:
#17 Remove Missing Values

df.dropna(inplace=True)

In [39]:
#18 Unique Values

print(df["Species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [40]:
#19 Value Counts

print(df["Species"].value_counts())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [43]:
#20 Group By

df.groupby("Species").mean(numeric_only=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [44]:
#21 Rename Columns

df.rename(columns={"SepalLengthCm":"Sepal_Length"},inplace=True)

df.head()

   Id  Sepal_Length  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1           5.1           3.5            1.4           0.2  Iris-setosa
1   2           4.9           3.0            1.4           0.2  Iris-setosa
2   3           4.7           3.2            1.3           0.2  Iris-setosa
3   4           4.6           3.1            1.5           0.2  Iris-setosa
4   5           5.0           3.6            1.4           0.2  Iris-setosa

In [45]:
#22 Export CSV

df.to_csv("iris_output.csv",index=False)

End Summary:
------------

Topics Covered :-

✔ Series
✔ DataFrame
✔ Read CSV
✔ Head
✔ Tail
✔ Info
✔ Describe
✔ Columns
✔ Row Selection
✔ Column Selection
✔ Filtering
✔ Sorting
✔ Add Column
✔ Delete Column
✔ Missing Values
✔ Fill Missing Values
✔ Drop Missing Values
✔ Unique Values
✔ Value Counts
✔ Group By
✔ Rename Columns
✔ Export CSV