In [1]:
#1 Import Libraries

import pandas as pd
import numpy as np

In [2]:
#2 Load Dataset

df = pd.read_csv("automobileEDA.csv")

df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [3]:
#3 Dataset Information

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    int64
 2   make               201 non-null    object
 3   aspiration         201 non-null    object
 4   num-of-doors       201 non-null    object
 5   body-style         201 non-null    object
 6   drive-wheels       201 non-null    object
 7   engine-location    201 non-null    object
 8   wheel-base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb-weight        201 non-null    int64
 13  engine-type        201 non-null    object
 14  num-of-cylinders   201 non-null    object
 15  engine-size        201 non-null    int64
 16  fuel-system        201 non-null    object
 17  bore               201 non-null    float64
 18  stroke             197 non-null    float64
 19  compression-ratio  201 non-null    float64
 20  horsepower         201 non-null    float64
 21  peak-rpm           201 non-null    float64
 22  city-mpg           201 non-null    int64
 23  highway-mpg        201 non-null    int64
 24  price              201 non-null    float64
 25  city-L/100km       201 non-null    float64
 26  horsepower-binned  200 non-null    object
 27  diesel             201 non-null    int64
 28  gas                201 non-null    int64
dtypes: float64(11), int64(8), object(10)
memory usage: 45.7+ KB
None

In [4]:
#4 Check Missing Values

print(df.isnull().sum())

symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    1
diesel               0
gas                  0
dtype: int64

In [8]:
#5 Display Missing Values

df[df.isnull().any(axis=1)]

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
46,0,122,jaguar,std,two,sedan,rwd,front,102.0,0.921192,...,11.5,262.0,5000.0,13,17,36000.0,18.076923,NaN,0,1
52,3,150,mazda,std,two,hatchback,rwd,front,95.3,0.812110,...,9.4,101.0,6000.0,17,23,10945.0,13.823529,Low,0,1
53,3,150,mazda,std,two,hatchback,rwd,front,95.3,0.812110,...,9.4,101.0,6000.0,17,23,11845.0,13.823529,Low,0,1
54,3,150,mazda,std,two,hatchback,rwd,front,95.3,0.812110,...,9.4,101.0,6000.0,17,23,13645.0,13.823529,Low,0,1
55,3,150,mazda,std,two,hatchback,rwd,front,95.3,0.812110,...,9.4,135.0,6000.0,16,23,15645.0,14.687500,Medium,0,1

In [11]:
#6 Fill Missing Values

df["price"].fillna(df["price"].mean(),inplace=True)

df.head()

C:\Users\vikra\AppData\Local\Temp\ipykernel_5608\3061094699.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].mean(),inplace=True)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [12]:
#7 Drop Missing Values

df.dropna(inplace=True)

print(df.shape)

(196, 29)

In [13]:
#8 Find Duplicate Rows

print(df.duplicated().sum())

0

In [14]:
#9 Remove Duplicate Rows

df.drop_duplicates(inplace=True)

print(df.shape)

(196, 29)

In [15]:
#10 Rename Columns

df.rename(columns={"horsepower":"HorsePower"}, inplace=True)

print(df.columns)

Index(['symboling', 'normalized-losses', 'make', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'HorsePower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price',
       'city-L/100km', 'horsepower-binned', 'diesel', 'gas'],
      dtype='object')

In [16]:
#11 Change Data Type

df["price"] = df["price"].astype(float)

print(df.dtypes)

symboling              int64
normalized-losses      int64
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
HorsePower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
city-L/100km         float64
horsepower-binned     object
diesel                 int64
gas                    int64
dtype: object

In [18]:
#12 Remove Extra Spaces

df["make"] = df["make"].str.strip()

df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,HorsePower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [21]:
#13 Convert Text to Uppercase

df["make"] = df["make"].str.upper()

df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,HorsePower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,ALFA-ROMERO,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,ALFA-ROMERO,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,AUDI,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,AUDI,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [20]:
#14 Replace Values

df["fuel-type"].replace("gas","petrol", inplace=True)

print(df.head())

KeyError: 'fuel-type'

In [23]:
#15 Detect Outliers (IQR Method)

Q1 = df["price"].quantile(0.25)

Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

outliers = df[(df["price"] < (Q1 - 1.5*IQR)) |
              (df["price"] > (Q3 + 1.5*IQR))]

outliers

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,HorsePower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
14,0,122,BMW,std,four,sedan,rwd,front,103.5,0.908217,...,8.0,182.0,5400.0,16,22,30760.0,14.687500,High,0,1
15,0,122,BMW,std,two,sedan,rwd,front,103.5,0.931283,...,8.0,182.0,5400.0,16,22,41315.0,14.687500,High,0,1
16,0,122,BMW,std,four,sedan,rwd,front,110.0,0.946660,...,8.0,182.0,5400.0,15,20,36880.0,15.666667,High,0,1
44,0,145,JAGUAR,std,four,sedan,rwd,front,113.0,0.959154,...,8.1,176.0,4750.0,15,19,32250.0,15.666667,High,0,1
45,0,122,JAGUAR,std,four,sedan,rwd,front,113.0,0.959154,...,8.1,176.0,4750.0,15,19,35550.0,15.666667,High,0,1
67,-1,93,MERCEDES-BENZ,turbo,four,sedan,rwd,front,115.6,0.973570,...,21.5,123.0,4350.0,22,25,31600.0,10.681818,Medium,1,0
68,-1,122,MERCEDES-BENZ,std,four,sedan,rwd,front,115.6,0.973570,...,8.3,155.0,4750.0,16,18,34184.0,14.687500,Medium,0,1
69,3,142,MERCEDES-BENZ,std,two,convertible,rwd,front,96.6,0.866410,...,8.3,155.0,4750.0,16,18,35056.0,14.687500,Medium,0,1
70,0,122,MERCEDES-BENZ,std,four,sedan,rwd,front,120.9,1.000000,...,8.0,184.0,4500.0,14,16,40960.0,16.785714,High,0,1
71,1,122,MERCEDES-BENZ,std,two,hardtop,rwd,front,112.0,0.957232,...,8.0,184.0,4500.0,14,16,45400.0,16.785714,High,0,1
123,3,122,PORSCHE,std,two,hardtop,rwd,rear,89.5,0.811629,...,9.5,207.0,5900.0,17,25,32528.0,13.823529,High,0,1
124,3,122,PORSCHE,std,two,hardtop,rwd,rear,89.5,0.811629,...,9.5,207.0,5900.0,17,25,34028.0,13.823529,High,0,1
125,3,122,PORSCHE,std,two,convertible,rwd,rear,89.5,0.811629,...,9.5,207.0,5900.0,17,25,37028.0,13.823529,High,0,1

In [24]:
#16 Remove Outliers

df = df[(df["price"] >= (Q1 - 1.5*IQR)) &(df["price"] <= (Q3 + 1.5*IQR))]

In [25]:
#17 Check Unique Values

print(df["make"].unique())

['ALFA-ROMERO' 'AUDI' 'BMW' 'CHEVROLET' 'DODGE' 'HONDA' 'ISUZU' 'MAZDA'
 'MERCEDES-BENZ' 'MERCURY' 'MITSUBISHI' 'NISSAN' 'PEUGOT' 'PLYMOUTH'
 'PORSCHE' 'RENAULT' 'SAAB' 'SUBARU' 'TOYOTA' 'VOLKSWAGEN' 'VOLVO']

In [26]:
#18 Value Counts

print(df["make"].value_counts())

make
TOYOTA           32
NISSAN           18
MITSUBISHI       13
HONDA            13
MAZDA            13
VOLKSWAGEN       12
SUBARU           12
VOLVO            11
PEUGOT           11
DODGE             9
PLYMOUTH          7
SAAB              6
AUDI              6
BMW               5
ALFA-ROMERO       3
CHEVROLET         3
MERCEDES-BENZ     3
RENAULT           2
ISUZU             2
MERCURY           1
PORSCHE           1
Name: count, dtype: int64

In [28]:
#19 Sort Dataset

df.sort_values(by="price", ascending=False, inplace=True)

df.head()

C:\Users\vikra\AppData\Local\Temp\ipykernel_5608\1636289995.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by="price", ascending=False, inplace=True)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,HorsePower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
65,-1,93,MERCEDES-BENZ,turbo,four,wagon,rwd,front,110.0,0.917347,...,21.5,123.0,4350.0,22,25,28248.0,10.681818,Medium,1,0
66,0,93,MERCEDES-BENZ,turbo,two,hardtop,rwd,front,106.7,0.901009,...,21.5,123.0,4350.0,22,25,28176.0,10.681818,Medium,1,0
64,-1,93,MERCEDES-BENZ,turbo,four,sedan,rwd,front,110.0,0.917347,...,21.5,123.0,4350.0,22,25,25552.0,10.681818,Medium,1,0
13,1,122,BMW,std,four,sedan,rwd,front,103.5,0.908217,...,9.0,121.0,4250.0,20,25,24565.0,11.750000,Medium,0,1
8,1,158,AUDI,turbo,four,sedan,fwd,front,105.8,0.925997,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1

In [29]:
#20 Reset Index

df.reset_index(drop=True, inplace=True)

df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,HorsePower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,-1,93,MERCEDES-BENZ,turbo,four,wagon,rwd,front,110.0,0.917347,...,21.5,123.0,4350.0,22,25,28248.0,10.681818,Medium,1,0
1,0,93,MERCEDES-BENZ,turbo,two,hardtop,rwd,front,106.7,0.901009,...,21.5,123.0,4350.0,22,25,28176.0,10.681818,Medium,1,0
2,-1,93,MERCEDES-BENZ,turbo,four,sedan,rwd,front,110.0,0.917347,...,21.5,123.0,4350.0,22,25,25552.0,10.681818,Medium,1,0
3,1,122,BMW,std,four,sedan,rwd,front,103.5,0.908217,...,9.0,121.0,4250.0,20,25,24565.0,11.750000,Medium,0,1
4,1,158,AUDI,turbo,four,sedan,fwd,front,105.8,0.925997,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1

In [30]:
#21 Save Clean Dataset

df.to_csv("cleaned_automobile.csv", index=False)

End Summary:
------------

Topics Covered :-

✔ Load Dataset
✔ Dataset Information
✔ Missing Values
✔ Fill Missing Values
✔ Drop Missing Values
✔ Duplicate Records
✔ Remove Duplicates
✔ Rename Columns
✔ Change Data Types
✔ Remove Extra Spaces
✔ Uppercase Conversion
✔ Replace Values
✔ Detect Outliers
✔ Remove Outliers
✔ Unique Values
✔ Value Counts
✔ Sorting
✔ Reset Index
✔ Export Clean Dataset